openapi: "3.0.3"

info:
  title: xyz class management
  description: class management tools for every school
  version: 1.0.0

servers:
  - url: http://localhost:8080/api

paths:
  /v1/students/profile:
    get:
      tags:
        - students profile
      summary: get students information
      responses:
        "200":
          description: get all students information
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/students-profile"
                    minItems: 0
        "500":
          $ref: "#/components/responses/500"

    post:
      tags:
        - students profile
      summary: create a new student
      requestBody:
        $ref: "#/components/requestBodies/insertOrUpdateStudents"
      responses:
        "200":
          description: create a new student success
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  status:
                    type: string
                    example: "OK"
                  data:
                    $ref: "#components/schemas/insertOrUpdateStudents"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"

  /v1/student/profile/{id}:
    get:
      tags:
        - students profile
      summary: get a student information
      parameters:
        - $ref: "#components/parameters/id"
      responses:
        "200":
          description: get a student information success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/students-profile"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    patch:
      description: update a student information
      tags:
        - students profile
      parameters:
        - $ref: "#components/parameters/id"
      requestBody:
        $ref: "#/components/requestBodies/insertOrUpdateStudents"
      responses:
        "200":
          description: update a student information success
          content:
            application/json:
              schema:
                $ref: "#components/schemas/insertOrUpdateStudents"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"

components:
  schemas:
    classes:
      type: object
      properties:
        _id:
          type: string
          example: as8ohr43843n
        name:
          type: string
          example: mathematics
        room:
          type: string
          nullable: true
          example: online
        instructors:
          type: array
          items:
            $ref: "#/components/schemas/instructors"
          minimum: 0
        assignments:
          type: array
          items:
            $ref: "#/components/schemas/assignments"
        status:
          type: string
          enum:
            - scheduled
            - ongoing
            - completed
            - cancelled
          default: scheduled
          example: scheduled
        notes:
          type: string
          example: trial class for newcomers
          nullable: true
      minProperties: 2
      additionalProperties: false

    instructors:
      type: object
      properties:
        _id:
          type: string
          example: n2kohvj23kl
        name:
          type: string
          example: "Noora"
        created_date:
          type: string
          format: date-time
        updated_date:
          type: string
          format: date-time
      minProperties: 2
      maxProperties: 5
      additionalProperties: false

    students:
      type: object
      properties:
        _id:
          type: string
          example: b12asdf23ksa3
        name:
          type: string
          example: Joko
        created_date:
          type: string
          format: date-time
        updated_date:
          type: string
          format: date-time

    students-profile:
      type: object
      properties:
        _id:
          type: string
          example: b12asdf23ksa3
        name:
          type: string
          example: "Joko"
        classes:
          type: array
          items:
            $ref: "#/components/schemas/classes"
        created_date:
          type: string
          format: date-time
        updated_date:
          type: string
          format: date-time
      minProperties: 5
      maxProperties: 5
      additionalProperties: false

    assignments:
      type: object
      properties:
        _id:
          type: string
          example: f289huiayf98as
        name:
          type: string
          example: Practice yoga
        due:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - todo
            - working
            - done
          default: todo
          example: todo
        grade:
          type: number
          minimum: 0
          maximum: 100
          nullable: true
          default: null
          example: 80
      minProperties: 2
      additionalProperties: false

    errors:
      type: object
      properties:
        code:
          type: number
        status:
          type: string
        data:
          type: object
          properties:
            error:
              type: string

    insertOrUpdateStudents:
      type: object
      properties:
        name:
          type: string
          example: "Joko"

  parameters:
    id:
      in: path
      name: id
      required: true
      schema:
        type: number
        minimum: 1
      description: id of specified resource

  requestBodies:
    insertOrUpdateStudents:
      description: Request body to insert and update students data
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/insertOrUpdateStudents"

  responses:
    "400":
      description: Wrong input from the client
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errors"
          example:
            code: 400
            status: Bad Request
            data:
              error: column.ID validation error
    "401":
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errors"
          example:
            code: 401
            status: Unauthorized
            data:
              error: No token provided
    "404":
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errors"
          example:
            code: 404
            status: Not Found
            data:
              error: User ID x8934yhf is not found!
    "500":
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errors"
          example:
            code: 500
            status: Internal Server Error
            data:
              error: pg.Name is not integer!
